### ISSUE TITLE
As a developer, I want the automated tests to run for each commit

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#54]
Given a commit to a branch
When the commit is pushed
Then the automated tests should run

In other words, the topology should be one run/action per one commit, and not one run/action per merge of a PR. This is consistent with the old pipeline.

**Comment by james-d-brown** [comment]
As far as I can see, the new pipeline does not execute all automated tests on each commit. This is problematic because a branched issue could have a very large number of commits before a PR is created and eventually merged.

I appreciate that we have moved from committing to the trunk to branching with each issue, but we should not change the topology of the automated tests, which should run on every commit for timely feedback.

Naturally, they should also run on merging a PR and should prevent that merge. When committing to a branch, the tests failing would not be any kind of block, but would provide timely feedback.

**Comment by epag** [comment]
This is a super easy fix. I originally choose not to go this path to encourage doing a draft PR, but I can add this in today

**Comment by james-d-brown** [comment]
Sounds good, thanks.

**Comment by epag** [comment]
Put the change in, just waiting to verify it passes automatic testing, but looking at the actions kicked off it kicked off when I pushed the change to my branch as well as when I opened the PR this time

**Comment by james-d-brown** [comment]
Evan, how do I witness this pipeline completing? For example, I just pushed against branch issue47 for issue #47. Where do I witness the pipeline steps running and, eventually, passing or failing? Thanks.

**Comment by epag** [comment]
Actually I think I just saw the issue. Looks like you havent pulled against master since I made the workflow changes so you still have the old workflows where testing on every commit was not turned on. 

If you pull those changes it should start working. Let me know if that isnt the case though and ill re-open

**Comment by james-d-brown** [comment]
Oh, so this is branch-specific config, not general github config that spans all branches?

**Comment by epag** [comment]
> Oh, so this is branch-specific config, not general github config that spans all branches?

The workflows are defined in the `.github/workflows` directory in our codebase. So a branch will need to be updated in order to have those workflows. But no, it is not some github config, they live in the repo

**Comment by james-d-brown** [comment]
Got it, thanks, just merged master into my branch and I now see the workflow running.
